FROM openjdk:11-jdk

ENV LANG=C.UTF-8 \
    TZ=Asia/Tokyo

EXPOSE 8080

ADD target/spring-boot-share-favplace.war spring-boot-share-favplace.war

ENTRYPOINT [ "java", "-jar", "/spring-boot-share-favplace.war" ]
